export const PERMISSIONS = {
  ORDERS_VIEW: "orders.view",
  ORDERS_VIEW_OWN: "orders.view_own",
  ORDERS_CREATE: "orders.create",
  ORDERS_EDIT: "orders.edit",
  ORDERS_APPROVE: "orders.approve",
  ORDERS_CANCEL: "orders.cancel",
  ORDERS_PACK_SHIP: "orders.pack_ship",
  ORDERS_PAY: "orders.pay",
  ORDERS_DELETE: "orders.delete",
  ORDERS_EXPORT: "orders.excel.export",
  ORDERS_IMPORT: "orders.excel.import",

  PRODUCTS_VIEW: "products.view",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_EDIT: "products.edit",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_PRICE_EDIT: "products.price.edit",
  PRODUCTS_COST_VIEW: "products.cost.view",
  PRODUCTS_COST_EDIT: "products.cost.edit",
  PRODUCTS_STATUS_EDIT: "products.status.edit",
  PRODUCTS_VARIANT_CREATE: "products.variant.create",
  PRODUCTS_IMAGE_UPLOAD: "products.image.upload",
  PRODUCTS_MASTER_DATA_MANAGE: "products.master_data.manage",
  PRODUCTS_EXCEL_EXPORT: "products.excel.export",
  PRODUCTS_EXCEL_IMPORT: "products.excel.import",

  INVENTORY_VIEW: "inventory.view",
  INVENTORY_VALUE_VIEW: "inventory.value.view",
  INVENTORY_MANAGE: "inventory.manage",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  INVENTORY_LOGS_VIEW: "inventory.logs.view",
  INVENTORY_EXCEL_IMPORT: "inventory.excel.import",
  INVENTORY_EXCEL_AUDIT: "inventory.excel.audit",

  PURCHASE_RECEIPT_VIEW: "purchase_receipt.view",
  PURCHASE_RECEIPT_CREATE: "purchase_receipt.create",
  PURCHASE_RECEIPT_EDIT: "purchase_receipt.edit",
  PURCHASE_RECEIPT_REQUEST_PAYMENT: "purchase_receipt.request_payment",
  PURCHASE_RECEIPT_PAY: "purchase_receipt.pay",
  PURCHASE_RECEIPT_IMPORT_STOCK: "purchase_receipt.import_stock",
  PURCHASE_RECEIPT_COMPLETE: "purchase_receipt.complete",
  PURCHASE_RECEIPT_CANCEL: "purchase_receipt.cancel",
  PURCHASE_RECEIPT_RECEIVE: "purchase_receipt.receive",
  PURCHASE_RECEIPT_COST_VIEW: "purchase_receipt.cost.view",
  PURCHASE_RECEIPT_COST_EDIT: "purchase_receipt.cost.edit",

  STOCK_TRANSFER_VIEW: "stock_transfer.view",
  STOCK_TRANSFER_CREATE: "stock_transfer.create",
  STOCK_TRANSFER_EDIT: "stock_transfer.edit",
  STOCK_TRANSFER_CONFIRM: "stock_transfer.confirm",
  STOCK_TRANSFER_RECEIVE: "stock_transfer.receive",
  STOCK_TRANSFER_CANCEL: "stock_transfer.cancel",

  STOCKTAKE_VIEW: "stocktake.view",
  STOCKTAKE_CREATE: "stocktake.create",
  STOCKTAKE_EDIT: "stocktake.edit",
  STOCKTAKE_CONFIRM: "stocktake.confirm",
  STOCKTAKE_APPLY: "stocktake.apply",
  STOCKTAKE_EXCEL_EXPORT: "stocktake.excel.export",
  STOCKTAKE_EXCEL_IMPORT: "stocktake.excel.import",

  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_VIEW_OWN: "customers.view_own",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_EDIT: "customers.edit",

  CASH_VOUCHER_VIEW: "cash_voucher.view",
  CASH_VOUCHER_CREATE_RECEIPT: "cash_voucher.create_receipt",
  CASH_VOUCHER_EDIT_RECEIPT: "cash_voucher.edit_receipt",
  CASH_VOUCHER_CONFIRM_RECEIPT: "cash_voucher.confirm_receipt",
  CASH_VOUCHER_CANCEL_RECEIPT: "cash_voucher.cancel_receipt",
  CASH_VOUCHER_CREATE_PAYMENT: "cash_voucher.create_payment",
  CASH_VOUCHER_EDIT_PAYMENT: "cash_voucher.edit_payment",
  CASH_VOUCHER_CONFIRM_PAYMENT: "cash_voucher.confirm_payment",
  CASH_VOUCHER_CANCEL_PAYMENT: "cash_voucher.cancel_payment",
  CASH_VOUCHER_EXPORT: "cash_voucher.export",
  CASH_VOUCHER_AUDIT: "cash_voucher.audit",

  SUPPLIER_PAYMENTS_VIEW: "supplier_payments.view",
  SUPPLIER_PAYMENTS_COST_EDIT: "supplier_payments.cost.edit",
  SUPPLIER_PAYMENTS_PAY: "supplier_payments.pay",

  PROMOTIONS_VIEW: "promotions.view",
  PROMOTIONS_CREATE: "promotions.create",
  PROMOTIONS_EDIT: "promotions.edit",
  PROMOTIONS_CONFIRM: "promotions.confirm",
  PROMOTIONS_ACTIVATE: "promotions.activate",
  PROMOTIONS_PAUSE: "promotions.pause",
  PROMOTIONS_CANCEL: "promotions.cancel",
  PROMOTIONS_DELETE: "promotions.delete",

  FINANCE_VIEW: "finance.view",
  FINANCE_LOCAL_DELIVERY_VIEW: "finance.local_delivery.view",
  FINANCE_LOCAL_DELIVERY_CONFIRM: "finance.local_delivery.confirm",
  FINANCE_GHN_VIEW: "finance.ghn.view",
  FINANCE_GHN_IMPORT: "finance.ghn.import",
  FINANCE_PAYMENT_SOURCE_MANAGE: "finance.payment_source.manage",

  MENU_STAFF_TRANSFER: "menu.staff_transfer",
  STAFF_TRANSFER_BRANCH_VIEW: "staff.transfer_branch.view",
  STAFF_TRANSFER_BRANCH: "staff.transfer_branch",

  MENU_OMNI_INBOX: "menu.omni_inbox",
  MENU_OMNI_MESSAGES: "menu.omni_messages",
  MENU_OMNI_COMMENTS: "menu.omni_comments",
  MENU_OMNI_LIVESTREAM: "menu.omni_livestream",

  // Giữ tên constant OMNI_MESSAGES_* để không phải sửa controller import,
  // nhưng value phải khớp bộ quyền frontend/Role Template đang lưu trong DB.
  OMNI_MESSAGES_VIEW: "omni_inbox.view",
  OMNI_MESSAGES_REPLY: "omni_inbox.reply",
  OMNI_MESSAGES_ASSIGN: "omni_inbox.assign",
  OMNI_MESSAGES_MANAGE: "omni_inbox.settings",
  OMNI_MESSAGES_TAGS: "omni_inbox.tags.manage",
  OMNI_MESSAGES_NOTES: "omni_inbox.notes.manage",
  OMNI_MESSAGES_CREATE_ORDER: "omni_inbox.create_order",
} as const;
