export const PERMISSIONS = {
  MENU_DASHBOARD: "menu.dashboard",
  MENU_ORDERS: "menu.orders",
  MENU_CREATE_ORDER: "menu.create_order",
  MENU_POS: "menu.pos",
  MENU_RETURNS: "menu.returns",
  MENU_PRODUCTS: "menu.products",
  MENU_PROMOTIONS: "menu.promotions",
  MENU_PRODUCT_CATEGORIES: "menu.product_categories",
  MENU_SUPPLIERS: "menu.suppliers",
  MENU_CUSTOMERS: "menu.customers",
  MENU_INVENTORY: "menu.inventory",
  MENU_INVENTORY_LOGS: "menu.inventory_logs",
  MENU_PURCHASE_RECEIPT: "menu.purchase_receipt",
  MENU_STOCK_TRANSFER: "menu.stock_transfer",
  MENU_STOCKTAKE: "menu.stocktake",
  MENU_WAREHOUSE_MAP: "menu.warehouse_map",
  MENU_FINANCE: "menu.finance",
  MENU_SHIPPING_RECONCILE: "menu.shipping_reconcile",
  MENU_FINANCE_LOCAL_DELIVERY: "menu.finance_local_delivery",
  MENU_FINANCE_GHN_RECONCILIATION: "menu.finance_ghn_reconciliation",
  MENU_CASH_VOUCHER: "menu.cash_voucher",
  MENU_SUPPLIER_PAYMENTS: "menu.supplier_payments",
  MENU_REPORTS: "menu.reports",
  MENU_AUTOPILOT: "menu.autopilot",
  MENU_AI_CONTENT: "menu.ai_content",
  MENU_PERMISSIONS: "menu.permissions",
  MENU_SETTINGS: "menu.settings",
  MENU_PRINT_CENTER: "menu.print_center",
  MENU_PAYROLL: "menu.payroll",
  MENU_PAYROLL_CONFIG: "menu.payroll_config",
  MENU_STAFF_TRANSFER: "menu.staff_transfer",
  MENU_OMNI_INBOX: "menu.omni_inbox",
  MENU_OMNI_MESSAGES: "menu.omni_messages",
  MENU_OMNI_COMMENTS: "menu.omni_comments",
  MENU_OMNI_LIVESTREAM: "menu.omni_livestream",

  PAYROLL_VIEW: "payroll.view",
  PAYROLL_CREATE: "payroll.create",
  PAYROLL_CALCULATE: "payroll.calculate",
  PAYROLL_EDIT: "payroll.edit",
  PAYROLL_LOCK: "payroll.lock",
  PAYROLL_MARK_PAID: "payroll.mark_paid",
  PAYROLL_CONFIG: "payroll.config",
  PAYROLL_EXPORT: "payroll.export",

  ORDERS_VIEW: "orders.view",
  ORDERS_VIEW_OWN: "orders.view_own",
  ORDERS_CREATE: "orders.create",
  ORDERS_EDIT: "orders.edit",
  ORDERS_APPROVE: "orders.approve",
  ORDERS_CANCEL: "orders.cancel",
  ORDERS_PACK_SHIP: "orders.pack_ship",
  ORDERS_PAY: "orders.pay",
  ORDERS_DELETE: "orders.delete",
  ORDERS_COPY: "orders.copy",
  ORDERS_PRINT: "orders.print",
  ORDERS_COD_EDIT: "orders.cod.edit",
  ORDERS_SHIPPING_FEE_EDIT: "orders.shipping_fee.edit",
  ORDERS_PAYMENT_SOURCE_EDIT: "orders.payment_source.edit",
  ORDERS_EXCEL_EXPORT: "orders.excel.export",
  ORDERS_EXCEL_IMPORT: "orders.excel.import",

  PRODUCTS_VIEW: "products.view",
  PRODUCTS_PRINT_LABEL: "products.print_label",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_EDIT: "products.edit",
  PRODUCTS_DELETE: "products.delete",
  PRODUCTS_PRICE_EDIT: "products.price.edit",
  PRODUCTS_COST_VIEW: "products.cost.view",
  PRODUCTS_COST_EDIT: "products.cost.edit",
  PRODUCTS_STATUS_EDIT: "products.status.edit",
  PRODUCTS_VARIANT_CREATE: "products.variant.create",
  PRODUCTS_IMAGE_UPLOAD: "products.image.upload",
  PRODUCTS_MASTER_DATA_MANAGE: "products.master_data.manage",
  PRODUCTS_EXCEL_EXPORT: "products.excel.export",
  PRODUCTS_EXCEL_IMPORT: "products.excel.import",

  INVENTORY_VIEW: "inventory.view",
  INVENTORY_MANAGE: "inventory.manage",
  INVENTORY_LOGS_VIEW: "inventory.logs.view",
  INVENTORY_VALUE_VIEW: "inventory.value.view",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  INVENTORY_EXCEL_IMPORT: "inventory.excel.import",
  INVENTORY_EXCEL_AUDIT: "inventory.excel.audit",

  PURCHASE_RECEIPT_VIEW: "purchase_receipt.view",
  PURCHASE_RECEIPT_CREATE: "purchase_receipt.create",
  PURCHASE_RECEIPT_EDIT: "purchase_receipt.edit",
  PURCHASE_RECEIPT_RECEIVE: "purchase_receipt.receive",
  PURCHASE_RECEIPT_REQUEST_PAYMENT: "purchase_receipt.request_payment",
  PURCHASE_RECEIPT_PAY: "purchase_receipt.pay",
  PURCHASE_RECEIPT_IMPORT_STOCK: "purchase_receipt.import_stock",
  PURCHASE_RECEIPT_COMPLETE: "purchase_receipt.complete",
  PURCHASE_RECEIPT_CANCEL: "purchase_receipt.cancel",
  PURCHASE_RECEIPT_COST_VIEW: "purchase_receipt.cost.view",
  PURCHASE_RECEIPT_COST_EDIT: "purchase_receipt.cost.edit",

  STOCK_TRANSFER_VIEW: "stock_transfer.view",
  STOCK_TRANSFER_CREATE: "stock_transfer.create",
  STOCK_TRANSFER_EDIT: "stock_transfer.edit",
  STOCK_TRANSFER_CONFIRM: "stock_transfer.confirm",
  STOCK_TRANSFER_RECEIVE: "stock_transfer.receive",
  STOCK_TRANSFER_CANCEL: "stock_transfer.cancel",
  STOCK_TRANSFER_AUTO_REBALANCE: "stock_transfer.auto_rebalance",

  STOCKTAKE_VIEW: "stocktake.view",
  STOCKTAKE_CREATE: "stocktake.create",
  STOCKTAKE_JOIN: "stocktake.join",
  STOCKTAKE_EDIT: "stocktake.edit",
  STOCKTAKE_SCAN: "stocktake.scan",
  STOCKTAKE_CONFIRM: "stocktake.confirm",
  STOCKTAKE_APPLY: "stocktake.apply",
  STOCKTAKE_CANCEL: "stocktake.cancel",
  STOCKTAKE_DELETE: "stocktake.delete",
  STOCKTAKE_EXCEL_EXPORT: "stocktake.excel.export",
  STOCKTAKE_EXCEL_IMPORT: "stocktake.excel.import",

  CUSTOMERS_VIEW: "customers.view",
  CUSTOMERS_VIEW_OWN: "customers.view_own",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_EDIT: "customers.edit",
  CUSTOMERS_DELETE: "customers.delete",
  CUSTOMERS_EXCEL_EXPORT: "customers.excel.export",
  CUSTOMERS_EXCEL_IMPORT: "customers.excel.import",

  RETURNS_VIEW: "returns.view",
  RETURNS_CREATE: "returns.create",
  RETURNS_CANCEL: "returns.cancel",
  RETURNS_PAY: "returns.pay",
  RETURNS_REFUND: "returns.refund",
  RETURNS_EXCEL_EXPORT: "returns.excel.export",

  CASH_VOUCHER_VIEW: "cash_voucher.view",
  CASH_VOUCHER_VIEW_RECEIPT: "cash_voucher.view_receipt",
  CASH_VOUCHER_VIEW_PAYMENT: "cash_voucher.view_payment",
  CASH_VOUCHER_CREATE_RECEIPT: "cash_voucher.create_receipt",
  CASH_VOUCHER_EDIT_RECEIPT: "cash_voucher.edit_receipt",
  CASH_VOUCHER_CONFIRM_RECEIPT: "cash_voucher.confirm_receipt",
  CASH_VOUCHER_CANCEL_RECEIPT: "cash_voucher.cancel_receipt",
  CASH_VOUCHER_CREATE_PAYMENT: "cash_voucher.create_payment",
  CASH_VOUCHER_EDIT_PAYMENT: "cash_voucher.edit_payment",
  CASH_VOUCHER_CONFIRM_PAYMENT: "cash_voucher.confirm_payment",
  CASH_VOUCHER_CANCEL_PAYMENT: "cash_voucher.cancel_payment",
  CASH_VOUCHER_EXPORT: "cash_voucher.export",
  CASH_VOUCHER_AUDIT: "cash_voucher.audit",

  FINANCE_VIEW: "finance.view",
  FINANCE_LOCAL_DELIVERY_VIEW: "finance.local_delivery.view",
  FINANCE_LOCAL_DELIVERY_CONFIRM: "finance.local_delivery.confirm",
  FINANCE_GHN_VIEW: "finance.ghn.view",
  FINANCE_GHN_IMPORT: "finance.ghn.import",
  FINANCE_PAYMENT_SOURCE_MANAGE: "finance.payment_source.manage",

  SUPPLIER_PAYMENTS_VIEW: "supplier_payments.view",
  SUPPLIER_PAYMENTS_COST_EDIT: "supplier_payments.cost.edit",
  SUPPLIER_PAYMENTS_PAY: "supplier_payments.pay",

  PROMOTIONS_VIEW: "promotions.view",
  PROMOTIONS_CREATE: "promotions.create",
  PROMOTIONS_EDIT: "promotions.edit",
  PROMOTIONS_CONFIRM: "promotions.confirm",
  PROMOTIONS_ACTIVATE: "promotions.activate",
  PROMOTIONS_PAUSE: "promotions.pause",
  PROMOTIONS_CANCEL: "promotions.cancel",
  PROMOTIONS_DELETE: "promotions.delete",
  PROMOTIONS_PRICE_POLICY_NONE: "promotions.price_policy.none",
  PROMOTIONS_PRICE_POLICY_ONLINE_DISCOUNT_ONLY: "promotions.price_policy.online_discount_only",
  PROMOTIONS_PRICE_POLICY_ONLINE_DISCOUNT_PRICE: "promotions.price_policy.online_discount_price",
  PROMOTIONS_PRICE_POLICY_POS_DISCOUNT_ONLY: "promotions.price_policy.pos_discount_only",
  PROMOTIONS_PRICE_POLICY_POS_DISCOUNT_PRICE: "promotions.price_policy.pos_discount_price",
  PROMOTIONS_PRICE_POLICY_ALL_CHANNELS_DISCOUNT_ONLY: "promotions.price_policy.all_channels_discount_only",
  PROMOTIONS_PRICE_POLICY_ALL_CHANNELS_DISCOUNT_PRICE: "promotions.price_policy.all_channels_discount_price",

  OMNI_INBOX_VIEW: "omni_inbox.view",
  OMNI_INBOX_REPLY: "omni_inbox.reply",
  OMNI_INBOX_ASSIGN: "omni_inbox.assign",
  OMNI_INBOX_TAGS_MANAGE: "omni_inbox.tags.manage",
  OMNI_INBOX_NOTES_MANAGE: "omni_inbox.notes.manage",
  OMNI_INBOX_CREATE_ORDER: "omni_inbox.create_order",
  OMNI_INBOX_CLOSE: "omni_inbox.close",
  OMNI_INBOX_EXPORT: "omni_inbox.export",
  OMNI_INBOX_SETTINGS: "omni_inbox.settings",

  // Compatibility constants: controller Omni cũ vẫn dùng tên OMNI_MESSAGES_*.
  // Value giữ cùng bộ permission omni_inbox.* đang dùng trong RBAC / role templates.
  OMNI_MESSAGES_VIEW: "omni_inbox.view",
  OMNI_MESSAGES_REPLY: "omni_inbox.reply",
  OMNI_MESSAGES_ASSIGN: "omni_inbox.assign",
  OMNI_MESSAGES_MANAGE: "omni_inbox.settings",
  OMNI_MESSAGES_TAGS: "omni_inbox.tags.manage",
  OMNI_MESSAGES_NOTES: "omni_inbox.notes.manage",
  OMNI_MESSAGES_CREATE_ORDER: "omni_inbox.create_order",

  OMNI_QUICK_REPLIES_VIEW: "omni_inbox.quick_replies.view",
  OMNI_QUICK_REPLIES_CREATE: "omni_inbox.quick_replies.create",
  OMNI_QUICK_REPLIES_EDIT: "omni_inbox.quick_replies.edit",
  OMNI_QUICK_REPLIES_DELETE: "omni_inbox.quick_replies.delete",
  OMNI_QUICK_REPLIES_DELETE_ALL: "omni_inbox.quick_replies.delete_all",
  OMNI_QUICK_REPLIES_IMPORT: "omni_inbox.quick_replies.import",
  OMNI_ASSIGNMENT_VIEW: "omni_inbox.assignment.view",
  OMNI_ASSIGNMENT_MANAGE: "omni_inbox.assignment.manage",
  OMNI_REPORTS_VIEW: "omni_inbox.reports.view",

  OMNI_COMMENTS_VIEW: "omni_comments.view",
  OMNI_COMMENTS_REPLY: "omni_comments.reply",
  OMNI_COMMENTS_HIDE: "omni_comments.hide",
  OMNI_LIVESTREAM_VIEW: "omni_livestream.view",
  OMNI_LIVESTREAM_REPLY: "omni_livestream.reply",

  // Mobile production hub / per-screen visibility
  MOBILE_HOME_PRODUCTION: "mobile.home.production",
  MOBILE_PRODUCTION_HUB_VIEW: "mobile.production_hub.view",
  MOBILE_PAGE_FABRIC_LIBRARY: "mobile.page.fabric_library",
  MOBILE_PAGE_DESIGN_SAMPLES: "mobile.page.design_samples",
  MOBILE_PAGE_MEASUREMENT_LIBRARY: "mobile.page.measurement_library",
  MOBILE_PAGE_FABRIC_RECEIPTS: "mobile.page.fabric_receipts",
  MOBILE_PAGE_PRODUCTION: "mobile.page.production",
  MOBILE_PAGE_ACCESSORIES: "mobile.page.accessories",

  // Web production / materials menus
  MENU_SAMPLE_FABRIC: "menu.sample_fabric",
  MENU_FABRIC_LIBRARY: "menu.fabric_library",
  MENU_DESIGN_SAMPLES: "menu.design_samples",
  MENU_MEASUREMENT_LIBRARY: "menu.measurement_library",
  MENU_FABRIC_RECEIPTS: "menu.fabric_receipts",

  // Fabric library
  FABRIC_LIBRARY_VIEW: "fabric_library.view",
  FABRIC_LIBRARY_CREATE: "fabric_library.create",
  FABRIC_LIBRARY_EDIT: "fabric_library.edit",
  FABRIC_LIBRARY_UPLOAD_IMAGES: "fabric_library.upload_images",
  FABRIC_LIBRARY_DELETE: "fabric_library.delete",

  // Design samples
  DESIGN_SAMPLE_VIEW: "design_sample.view",
  DESIGN_SAMPLE_CREATE: "design_sample.create",
  DESIGN_SAMPLE_EDIT: "design_sample.edit",
  DESIGN_SAMPLE_UPLOAD_IMAGES: "design_sample.upload_images",
  DESIGN_SAMPLE_DELETE: "design_sample.delete",

  // Sample dispatch
  SAMPLE_DISPATCH_VIEW: "sample_dispatch.view",
  SAMPLE_DISPATCH_CREATE: "sample_dispatch.create",
  SAMPLE_DISPATCH_EDIT: "sample_dispatch.edit",
  SAMPLE_DISPATCH_DELETE: "sample_dispatch.delete",

  // Measurement library
  MEASUREMENT_LIBRARY_VIEW: "measurement_library.view",
  MEASUREMENT_LIBRARY_CREATE: "measurement_library.create",
  MEASUREMENT_LIBRARY_EDIT: "measurement_library.edit",
  MEASUREMENT_LIBRARY_DELETE: "measurement_library.delete",

  MENU_PRODUCTION: "menu.production",
  PRODUCTION_VIEW: "production.view",
  PRODUCTION_CREATE: "production.create",
  PRODUCTION_SOURCE_SAMPLE_VIEW: "production.source.sample.view",
  PRODUCTION_STEP_1: "production.step1",
  PRODUCTION_STEP_2: "production.step2",
  PRODUCTION_STEP_3: "production.step3",
  PRODUCTION_STEP_4: "production.step4",
  PRODUCTION_STEP_5: "production.step5",
  PRODUCTION_STEP_6: "production.step6",
  PRODUCTION_EDIT: "production.edit",
  PRODUCTION_CALCULATE: "production.calculate",
  PRODUCTION_MANAGE: "production.manage",
  MENU_ACCESSORIES: "menu.accessories",
  ACCESSORIES_VIEW: "accessories.view",
  ACCESSORIES_COST_VIEW: "accessories.cost.view",
  ACCESSORIES_SUPPLIER_IDENTITY_VIEW: "accessories.supplier_identity.view",
  ACCESSORIES_MANAGE: "accessories.manage",
  ACCESSORIES_STOCK: "accessories.stock",

  // Fabric receipt
  FABRIC_RECEIPT_VIEW: "fabric_receipt.view",
  FABRIC_RECEIPT_FABRIC_BOARD_LINK: "fabric_receipt.fabric_board_link",
  FABRIC_RECEIPT_CREATE: "fabric_receipt.create",
  FABRIC_RECEIPT_EDIT: "fabric_receipt.edit",
  FABRIC_RECEIPT_MEASURE: "fabric_receipt.measure",
  FABRIC_RECEIPT_UPLOAD_IMAGES: "fabric_receipt.upload_images",
  FABRIC_RECEIPT_APPROVE_VARIANCE: "fabric_receipt.approve_variance",
  FABRIC_RECEIPT_COMPLETE: "fabric_receipt.complete",
  FABRIC_RECEIPT_CANCEL: "fabric_receipt.cancel",
  FABRIC_RECEIPT_DELETE: "fabric_receipt.delete",

  // Fabric receipt sensitive fields
  FABRIC_RECEIPT_SUPPLIER_IDENTITY_VIEW: "fabric_receipt.supplier_identity.view",
  FABRIC_RECEIPT_COST_VIEW: "fabric_receipt.cost.view",
  FABRIC_RECEIPT_COST_EDIT: "fabric_receipt.cost.edit",

  PERMISSIONS_VIEW: "permissions.view",
  PERMISSIONS_MANAGE: "permissions.manage",
  SYSTEM_MANAGE: "system.manage",
  BRANCHES_MANAGE: "branches.manage",
  STAFF_MANAGE: "staff.manage",
  STAFF_TRANSFER_BRANCH_VIEW: "staff.transfer_branch.view",
  STAFF_TRANSFER_BRANCH: "staff.transfer_branch",
  AUDIT_VIEW: "audit.view",
  CARRIERS_MANAGE: "carriers.manage",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS] | "*" | string;

export function uniquePermissions(values: Array<string | null | undefined>) {
  return Array.from(new Set(values.map((v) => String(v || "").trim()).filter(Boolean)));
}
